
export const Status = {
  METHOD_NOT_FOUND: 'METHOD_NOT_FOUND',
  METHOD_SUCCESS: 'METHOD_SUCCESS',
  METHOD_ERROR: 'METHOD_ERROR',
  METHOD_ASYNC: 'METHOD_ASYNC',
  METHOD_READY: 'METHOD_READY',
  METHOD_DESTROY: 'METHOD_DESTROY',
  METHOD_TIMEOUT: 'METHOD_TIMEOUT'
};
